keys:
  # Cette clé sera remplacée par votre clé publique après génération
  - &titi age1wvx404flwc4zsx84zzpkd48zvktfw4vfuxy2h7auqrfy9k0hvsms4ygwdt
creation_rules:
  # Règle générale pour tous les secrets
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *titi
  # Règles spécifiques par host si nécessaire
  - path_regex: hosts/.*/secrets/.*\.yaml$
    key_groups:
      - age:
          - *titi
